### ISSUE TITLE
IOError: File graph#.pb.meta does not exist.

### ISSUE THREAD

**Issue by rohitmit07** [dhwajraj/deep-siamese-text-similarity#18]
@dhwajraj : please look into this issue and suggest what to do

on running : 
python eval.py --model graph#.pb
error comes **IOError: File graph#.pb.meta does not exist.**

if i run:
python eval.py --model runs/1502343870/checkpoints/model-9000
error comes 
Traceback (most recent call last):
  File "eval.py", line 69, in <module>
    sim = graph.get_operation_by_name("accuracy/temp_sim").outputs[0]
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 2712, in get_operation_by_name
    return self.as_graph_element(name, allow_tensor=False, allow_operation=True)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 2584, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 2644, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'accuracy/temp_sim' refers to an Operation not in the graph."

**Comment by rohitmit07** [comment]
@dhwajraj : please reply

**Comment by dhwajraj** [comment]
@rohitmit07 your model is trained on older version of code whereas you are running code on newer version of the code. please take fresh checkout of master and retrain the model.

**Comment by sharanthejal** [comment]
@dhwajraj Even with the latest version of the code i am getting the same error as @rohitmit07  mentioned.
Kindly, have a look into it once.

**Comment by Akirato** [comment]
Any updates in the thread?

**Comment by R1994** [comment]
@dhwajraj hello,i use required tensorflow  version but i still meet this question,can you give some help?

**Comment by aimaaonline** [comment]
i am facing same probelm.when i run eval.py the message on terminal is as follows:PLEASE HAVE A LOK AND REPLY ASAP

$python3 eval.py --model graph#.pb

Parameters:
ALLOW_SOFT_PLACEMENT=True
BATCH_SIZE=64
CHECKPOINT_DIR=
EVAL_FILEPATH=validation.txt0
LOG_DEVICE_PLACEMENT=False
MODEL=graph#.pb
VOCAB_FILEPATH=runs/1512222837/checkpoints/vocab

Loading testing/labelled data from validation.txt0
Traceback (most recent call last):
  File "eval.py", line 38, in <module>
    x1_test,x2_test,y_test = inpH.getTestDataSet(FLAGS.eval_filepath, FLAGS.vocab_filepath, 30)
  File "/home/seemab/seemab/siamese-text-similarity/input_helpers.py", line 213, in getTestDataSet
    vocab_processor = vocab_processor.restore(vocab_path)
  File "/home/seemab/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/preprocessing/text.py", line 226, in restore
    return pickle.loads(f.read())
  File "/home/seemab/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 119, in read
    self._preread_check()
  File "/home/seemab/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 79, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/seemab/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: runs/1512222837/checkpoints/vocab; No such file or directory

**Comment by wakamd** [comment]
Did you check the path to vocab file? some thing like "/home/me/cnn/runs/1518703649/checkpoints/" ?
remember to check that your '1512222837' could be different after training. I had the same problem but solved it by changing the path to the vocab file

**Comment by aimaaonline** [comment]
i want to change the ouptu of last layer.i want the similarity 1-5.how can
i do?
