### ISSUE TITLE
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them

### ISSUE THREAD

**Issue by KanimozhiU** [dhwajraj/deep-siamese-text-similarity#19]
Traceback (most recent call last):
  File "eval.py", line 8, in <module>
    from tensorflow.contrib import learn
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 31, in <module>
    from tensorflow.contrib import factorization
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/__init__.py", line 88, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/home/kanimozhiu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/home/kanimozhiu/anaconda3/lib/python3.5/site-packages/dask/dataframe/__init__.py", line 1, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/home/kanimozhiu/anaconda3/lib/python3.5/site-packages/dask/dataframe/core.py", line 23, in <module>
    from .. import array as da
  File "/home/kanimozhiu/anaconda3/lib/python3.5/site-packages/dask/array/__init__.py", line 4, in <module>
    from .core import (Array, stack, concatenate, take, tensordot, transpose,
  File "/home/kanimozhiu/anaconda3/lib/python3.5/site-packages/dask/array/core.py", line 13, in <module>
    from toolz.curried import (pipe, partition, concat, unique, pluck, join, first,
  File "/home/kanimozhiu/anaconda3/lib/python3.5/site-packages/toolz/curried/__init__.py", line 53, in <module>
    _curry_namespace(vars(toolz)),
  File "/home/kanimozhiu/anaconda3/lib/python3.5/site-packages/toolz/curried/__init__.py", line 48, in _curry_namespace
    for name, f in ns.items() if '__' not in name
  File "/home/kanimozhiu/anaconda3/lib/python3.5/site-packages/toolz/curried/__init__.py", line 48, in <genexpr>
    for name, f in ns.items() if '__' not in name
  File "/home/kanimozhiu/anaconda3/lib/python3.5/site-packages/toolz/curried/__init__.py", line 42, in _should_curry
    return (callable(f) and _nargs(f) > 1 or f in do_curry)
  File "/home/kanimozhiu/anaconda3/lib/python3.5/site-packages/toolz/curried/__init__.py", line 35, in _nargs
    return len(inspect.getargspec(f).args)
  File "/home/kanimozhiu/anaconda3/lib/python3.5/inspect.py", line 1050, in getargspec
    raise ValueError("Function has keyword-only arguments or annotations"
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
Error on predict.py. How to fix it?

**Comment by dhwajraj** [comment]
use python 2.7

**Comment by KanimozhiU** [comment]
Traceback (most recent call last):
  File "eval.py", line 41, in <module>
    x1_test,x2_test,y_test = inpH.getTestDataSet(FLAGS.eval_filepath, FLAGS.vocab_filepath, 30)
  File "/home/kanimozhiu/Documents/deep-siamese-text-similarity-master/input_helpers.py", line 141, in getTestDataSet
    x1_temp,x2_temp,y = self.getTsvTestData(data_path)
  File "/home//kanimozhiu//Documents/deep-siamese-text-similarity-master/input_helpers.py", line 53, in getTsvTestData
    for line in open(filepath):
IOError: [Errno 2] No such file or directory: 'match_valid.tsv'

This is the error occurred on Python 2.7

**Comment by zhanghuan18332552065** [comment]
I also have same problem in python3.5 on windows, but it can run on linux, and how did you solve it?
