### ISSUE TITLE
pickle error when running train.py

### ISSUE THREAD

**Issue by cpetroaca** [dhwajraj/deep-siamese-text-similarity#20]
Using python 3.5.2 and tensorflow 1.3.0.
I'm getting this when running train.py:

Traceback (most recent call last):
  File "C:\Data\Apps\eclipse-jee-oxygen-R-win32-x86_64\plugins\org.python.pydev_5.9.2.201708151115\pysrc\pydevd.py", line 1621, in <module>
    main()
  File "C:\Data\Apps\eclipse-jee-oxygen-R-win32-x86_64\plugins\org.python.pydev_5.9.2.201708151115\pysrc\pydevd.py", line 1615, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Data\Apps\eclipse-jee-oxygen-R-win32-x86_64\plugins\org.python.pydev_5.9.2.201708151115\pysrc\pydevd.py", line 1022, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Data\Apps\eclipse-jee-oxygen-R-win32-x86_64\plugins\org.python.pydev_5.9.2.201708151115\pysrc\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\cpetroaca\workspace\tensorflow\Siamese_Networks\train.py", line 111, in <module>
    vocab_processor.save(os.path.join(checkpoint_dir, "vocab"))
  File "C:\Users\cpetroaca\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\preprocessing\text.py", line 213, in save
    f.write(pickle.dumps(self))
_pickle.PicklingError: args[0] from __newobj__ args has the wrong class

**Comment by Sue52nlp** [comment]
i meet the same problem, do you have solve it?

**Comment by cpetroaca** [comment]
No. I don't have much knowledge of Python and I don't want to start digging through the code now. I just needed something that works as is.

**Comment by Sue52nlp** [comment]
have you find another effective codes?   i have solve the problem. you can modify input_helpers.py
and modify the code as this.

        vocab_processor = learn.preprocessing.VocabularyProcessor(max_document_length)
        vocab_processor.fit_transform(np.concatenate((x2_text,x1_text),axis=0))
        # vocab_processor = MyVocabularyProcessor(max_document_length,min_frequency=0)
        # vocab_processor.fit_transform(np.concatenate((x2_text,x1_text),axis=0))

**Comment by cpetroaca** [comment]
Cool Thanks. I'll try that.
I also tried this guy's implementation : https://medium.com/@eliorcohen/implementing-malstm-on-kaggles-quora-question-pairs-competition-8b31b0b16a07. There's a link to a github repo in the beginning.  
It does sentence similarity which I am interested in. No phrase similarity.
I got it training for around 10 epochs out of 50, which took around 2hrs and it got to 80% accuracy on it's validation set.

**Comment by Sue52nlp** [comment]
Thank you for you reply,  what you recommend is exactly what I want. I want to find a method that does sentence similarity. I'll try it.

**Comment by cpetroaca** [comment]
Did you find any other implementation that you can share?

**Comment by Sue52nlp** [comment]
you can see https://github.com/nelson-liu/paraphrase-id-tensorflow. It may help you.  But I haven't tried it. I'm just beginning to study the sentence similarity. 
I trid the project you shared, but it lacks of the code which save the model, or reload the model ,  or input another new sentence pair  and output the similarity.

**Comment by cpetroaca** [comment]
That's true but those can be easily added once the core model is functional.

**Comment by Sue52nlp** [comment]
hi
    have you load the model which has been trained to predict the question pairs. I did that, but the same code, The results of each run are different. Did you meet the same problem, and did you solve it?
    Looking forward to your reply
    Thank you

**Comment by aimaaonline** [comment]
thank you Sue52nlp commented on Oct 25, 2017
it really works

    vocab_processor = learn.preprocessing.VocabularyProcessor(max_document_length)
    vocab_processor.fit_transform(np.concatenate((x2_text,x1_text),axis=0))
    # vocab_processor = MyVocabularyProcessor(max_document_length,min_frequency=0)
    # vocab_processor.fit_transform(np.concatenate((x2_text,x1_text),axis=0))
