### ISSUE TITLE
how to evalute model...

### ISSUE THREAD

**Issue by aimaaonline** [dhwajraj/deep-siamese-text-similarity#33]
while executing eval.py .whe i run the command :python3 eval.py --model graph#.pb 
I  got error. I am using python 3.5 and i executed the train.py for 1500 epochs.
please reply ASAP
the Erorr is 
Parameters:
ALLOW_SOFT_PLACEMENT=True
BATCH_SIZE=64
CHECKPOINT_DIR=
EVAL_FILEPATH=validation.txt0
LOG_DEVICE_PLACEMENT=False
MODEL=graph#.pb
VOCAB_FILEPATH=runs/1516694831/checkpoints/vocab

Loading testing/labelled data from validation.txt0

Evaluating...

graph#.pb
2018-01-26 13:16:19.735451: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "eval.py", line 54, in <module>
    saver = tf.train.import_meta_graph("{}.meta".format(checkpoint_file))
  File "/home/seemab/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1803, in import_meta_graph
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "/home/seemab/.local/lib/python3.5/site-packages/tensorflow/python/framework/meta_graph.py", line 555, in read_meta_graph_file
    raise IOError("File %s does not exist." % filename)
OSError: File graph#.pb.meta does not exist.

Regards,

**Comment by aimaaonline** [comment]
issue resolved by using command python3 eval.py
change runs/_________________
folder name in runs and model no in checkpoint folder in runs folder
