### ISSUE TITLE
AttributeError when tf's version is 1.5

### ISSUE THREAD

**Issue by Vigilans-Yea** [dhwajraj/deep-siamese-text-similarity#39]
When running train.py, I came into an error:

```
Traceback (most recent call last):
  File "train.py", line 42, in <module>
    FLAGS._parse_flags()
  File "/home/vigilans/.local/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/home/vigilans/.local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 470, in __getattr__
    raise AttributeError(name)
AttributeError: _parse_flags
```

After some investigation, I found out that it is because `TensorFlow v1.5` remove the existence of `_parse_flags` attribute (it is reasonable given that this attribute is a private method with one underscore "_" in the beginning).

I think there must be a reason to write it this way in the environment of tf v1.2, so I wonder if you will repair this issue for tf v15 situation?

**Comment by Vigilans-Yea** [comment]
@mautc12 

Comment `FLAGS._parse_flags()` and everything will be okay, as all the flags are implicitly parsed since tf v1.5 and a `_parse_flags` is no longer needed.

**Comment by mautc12** [comment]
Thank @Vigilans-Yea , I am reading this coding on the github: https://github.com/dennybritz/cnn-text-classification-tf, when I was running file train.py which has error:
![image](https://user-images.githubusercontent.com/26129055/37699037-85bf26d0-2d20-11e8-911b-4f4d510f3e6b.png)
Can you help me, I am using Tensorflow's version 1.6.0
Thank you!

**Comment by Vigilans-Yea** [comment]
@mautc12

``` 
Trackback:
   File "C:\...\train.py", line 38, in <module>
     FLAGS._parse_flags()
```

So just switch to line 38 and delete/comment the FLAGS._parse_flags() function call.

**Comment by mautc12** [comment]
@Vigilans-Yea Very good, they worked, thank you very much

**Comment by vmvahdatpour** [comment]
python 2.7
tensorflow 1.4.0

FLAGS._parse_flags() not support any longer use FLAGS(sys.argv) instead. (call the python object)
