### ISSUE TITLE
python train.py error.

### ISSUE THREAD

**Issue by daogangtang** [dhwajraj/deep-siamese-text-similarity#5]
```
mike@Vostro-3653:~/works/deep-siamese-text-similarity$ uname -a
Linux Vostro-3653 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```

```
mike@Vostro-3653:~/works/deep-siamese-text-similarity$ python train.py 

Parameters:
ALLOW_SOFT_PLACEMENT=True
BATCH_SIZE=64
CHECKPOINT_EVERY=1000
DROPOUT_KEEP_PROB=0.5
EMBEDDING_DIM=100
EVALUATE_EVERY=1000
HIDDEN_UNITS=50
L2_REG_LAMBDA=0.0
LOG_DEVICE_PLACEMENT=False
NUM_EPOCHS=300
TRAINING_FILES=person_match.train2

Loading training data from person_match.train2
Building vocabulary
Length of loaded vocabulary =81
dumping validation 0
Train/Dev split for person_match.train2: 35634/3960
starting graph def
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
started session
Traceback (most recent call last):
  File "train.py", line 64, in <module>
    batch_size=FLAGS.batch_size)
  File "/home/mike/works/deep-siamese-text-similarity/siamese_network.py", line 77, in __init__
    self.out1=self.BiRNN(self.embedded_chars1, self.dropout_keep_prob, "side1", embedding_size, sequence_length)
  File "/home/mike/works/deep-siamese-text-similarity/siamese_network.py", line 23, in BiRNN
    x = tf.split(0, n_steps, x)
  File "/home/mike/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1198, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/home/mike/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3426, in _split
    num_split=num_split, name=name)
  File "/home/mike/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 509, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

```

**Comment by gallupliu** [comment]
please use tf_upgrade.py to upgrade scipt

**Comment by daogangtang** [comment]
Thx, I fix this by tf_upgrade.py and modify some code.

**Comment by daogangtang** [comment]
Another problem.

```
mike@Vostro-3653:~/works/deep-siamese-text-similarity_new$ python eval.py --model graph10999.pb

Parameters:
ALLOW_SOFT_PLACEMENT=True
BATCH_SIZE=64
CHECKPOINT_DIR=
EVAL_FILEPATH=match_valid.tsv
LOG_DEVICE_PLACEMENT=False
MODEL=graph10999.pb
VOCAB_FILEPATH=runs/1479874609/checkpoints/vocab

Loading testing/labelled data from match_valid.tsv
Traceback (most recent call last):
  File "eval.py", line 38, in <module>
    x1_test,x2_test,y_test = inpH.getTestDataSet(FLAGS.eval_filepath, FLAGS.vocab_filepath, 30)
  File "/home/mike/works/deep-siamese-text-similarity_new/input_helpers.py", line 141, in getTestDataSet
    x1_temp,x2_temp,y = self.getTsvTestData(data_path)
  File "/home/mike/works/deep-siamese-text-similarity_new/input_helpers.py", line 53, in getTsvTestData
    for line in open(filepath):
IOError: [Errno 2] No such file or directory: 'match_valid.tsv'

```

how to fix it?

**Comment by poornagurram** [comment]
Refer https://github.com/dhwajraj/deep-siamese-text-similarity/issues/4 this issue

**Comment by hustlrr** [comment]
@daogangtang May I ask how do you fix the first problem?

**Comment by daogangtang** [comment]
use  tf_upgrade.py and modify some code according prompt.

**Comment by chenfei2** [comment]
Traceback (most recent call last):
  File "train_1.py", line 98, in <module>
    vocab_processor.save(os.path.join(checkpoint_dir, "vocab"))
  File "//anaconda/envs/py3.6/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/preprocessing/text.py", line 213, in save
    f.write(pickle.dumps(self))
_pickle.PicklingError: args[0] from __newobj__ args has the wrong class
how to deal with the problem?

**Comment by R1994** [comment]
@chenfei2 i also meet same problem,and am struggling with it

**Comment by EnPython** [comment]
### **_pickle.PicklingError: args[0] from __newobj__ args has the wrong class**
when i run train.py file, i meet the problem as above and i would like to know how to fix it? thank u

**Comment by EnPython** [comment]
i think i fix this problem via reading the sharing experience, it tell me change some codes and it work
https://github.com/dhwajraj/deep-siamese-text-similarity/pull/28/commits/13c1af27e7e482b1745b90e59c36dd652793ec36
