### ISSUE TITLE
hi, IOError: [Errno 2] No such file or directory: 'match_valid.tsv'

### ISSUE THREAD

**Issue by daogangtang** [dhwajraj/deep-siamese-text-similarity#6]
hi, when I ran this code.

```
mike@Vostro-3653:~/works/deep-siamese-text-similarity_new$ python eval.py --model graph10999.pb

Parameters:
ALLOW_SOFT_PLACEMENT=True
BATCH_SIZE=64
CHECKPOINT_DIR=
EVAL_FILEPATH=match_valid.tsv
LOG_DEVICE_PLACEMENT=False
MODEL=graph10999.pb
VOCAB_FILEPATH=runs/1479874609/checkpoints/vocab

Loading testing/labelled data from match_valid.tsv
Traceback (most recent call last):
  File "eval.py", line 38, in <module>
    x1_test,x2_test,y_test = inpH.getTestDataSet(FLAGS.eval_filepath, FLAGS.vocab_filepath, 30)
  File "/home/mike/works/deep-siamese-text-similarity_new/input_helpers.py", line 141, in getTestDataSet
    x1_temp,x2_temp,y = self.getTsvTestData(data_path)
  File "/home/mike/works/deep-siamese-text-similarity_new/input_helpers.py", line 53, in getTsvTestData
    for line in open(filepath):
IOError: [Errno 2] No such file or directory: 'match_valid.tsv'

```

how to fix this? 
thx.

**Comment by daogangtang** [comment]
what is the format of match_valid.tsv?
